name: docker Build

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Package Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: lowercase repository name for docker tag
        run: |
          # https://github.community/t/additional-function-s-lowercase-uppercase/140632/2
          echo "REPO=${{ github.repository }}" >>${GITHUB_ENV}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/$REPO:${{ github.ref_name }},ghcr.io/$REPO:latest
          platforms: linux/amd64,linux/arm64
